# Eureka configuration for CI
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    export:
      enabled: false
#  opentelemetry:
#    tracing:
#      export:
#        otlp:
#          endpoint: http://localhost:4318/v1/traces
  otlp:
    metrics:
      export:
        enabled: false
#        url: http://localhost:4318/v1/metrics

app:
  allowedOrigins: http://localhost:3077
  accessTokenSecret: dummy-secret
  frontendBaseUrl: http://localhost:3077
