# Server properties
server:
  port: 8080

# Information for the info endpoint
info:
  app:
    environment: DEV
    name: API Gateway
    description: API Gateway Local Instance

# Spring application properties
spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URL}
      - optional:file:./env.properties
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

# Eureka configuration
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE}
  instance:
    preferIpAddress: true

# Management properties
management:
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, refresh, gateway

app:
  allowedOrigins: ${ALLOWED_ORIGINS}
  accessTokenSecret: ${ACCESS_TOKEN_SECRET}
  frontendBaseUrl: ${FRONTEND_BASE_URL}

# Logging properties
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
