# Server properties
server:
  port: 8080

# Information for the info endpoint
info:
  app:
    environment: DEV
    name: API Gateway
    description: API Gateway Local Instance

# Spring application properties
spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URL}
      - optional:file:./env.properties
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

# Eureka configuration
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE}
  instance:
    preferIpAddress: true

# Management properties
endpoints:
  shutdown:
    enabled: true
management:
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, refresh, shutdown, gateway

# Logging properties
logging:
  level:
    root: ERROR
    com.proactivetechie: INFO
    org.springframework: INFO
    org.hibernate: INFO
